title: First blog post
author: Daniel Donateli
email: daniel-donateli@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Learning GitHub Pages by making a blog

# social links
github_username:  daniel-donateli # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
